/*
 * generated by Xtext 2.24.0
 */
package org.eclipse.xtext.uma;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UmalStandaloneSetup extends UmalStandaloneSetupGenerated {

	public static void doSetup() {
		new UmalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
