/*
 * generated by Xtext 2.24.0
 */
package org.eclipse.xtext.uma;

import org.eclipse.xtext.uma.conversion.UmalConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UmalRuntimeModule extends AbstractUmalRuntimeModule {
	/*@Override
	public Class<UmalConverter> bindIValueConverterService() {
		return UmalConverter.class;
	}*/
}
