/*
 * generated by Xtext 2.24.0
 */
package org.eclipse.xtext.uma.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UmalUiModule extends AbstractUmalUiModule {

	public UmalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
