/*
 * generated by Xtext 2.24.0
 */
package org.xtext.epf.uma;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UmaRuntimeModule extends AbstractUmaRuntimeModule {
}
