/*
 * generated by Xtext 2.24.0
 */
package org.xtext.epf.uma;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UmaStandaloneSetup extends UmaStandaloneSetupGenerated {

	public static void doSetup() {
		new UmaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
