/*
 * generated by Xtext 2.24.0
 */
package org.xtext.epf.uma.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UmaUiModule extends AbstractUmaUiModule {

	public UmaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
